#!/usr/bin/python
import sys
import json
import os
import argparse

import datajunction

def main(argv):

    parser = argparse.ArgumentParser(
        prog = 'dataj_ls',
        description = 'Datajunction backup utility, file lister.')
    parser.add_argument('--version',
        help = 'output version number',
        action = 'version',
        version = datajunction.__version__)
    parser.add_argument('--json',
        help = 'output json entries',
        action = 'store_true')

    args = parser.parse_args()
    outputs = datajunction.datajunction.loadOutputs()
    if not len(outputs):
        print "Could not initialize any outputs."
        return 1
    for output in outputs:
        print ' >', output.name()
        for f in output.files():
            if args.json:
                print f
                continue
            
            print "%010s %s %s %s" % (
                f['type'],
                f['ctime'],
                f.get('digest_sha1', ''),
                f['location']['filename'])
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))


