#!/usr/bin/python
import sys
import json
import os
import argparse

import datajunction

def main(argv):

    parser = argparse.ArgumentParser(
        prog = 'dataj_ls',
        description = 'Datajunction backup utility, file lister.')
    parser.add_argument('--version',
        help = 'output version number',
        action = 'version',
        version = datajunction.__version__)

    outputs = datajunction.datajunction.loadOutputs()
    if not len(outputs):
        print "Could not initialize any outputs."
        return 1
    for output in outputs:
        print ' >', output.name()
        for f in output.files():
            print dir(f)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))


