#!/usr/bin/python
import sys
import json
import os
import argparse

import datajunction

def main(argv):

    parser = argparse.ArgumentParser(
        prog = 'dataj',
        description = 'Datajunction backup utility.')
    parser.add_argument('files',
        metavar = 'F',
        type = str,
        nargs = '+',
        help='files to write to output storages')
    #parser.add_argument('--recursive',
    #    help = 'recursive',
    #    action='store_true')
    parser.add_argument('--version',
        help = 'output version number',
        action = 'version',
        version = datajunction.__version__)

    args = parser.parse_args()
    #Convert filenames to system filename encoding
    args.files = [unicode(fileName, sys.getfilesystemencoding()) for fileName in args.files]
    outputs = datajunction.datajunction.loadOutputs()
    if not len(outputs):
        print "Could not initialize any outputs."
        return 1
    for fileName in args.files:
        print fileName
        fileName = os.path.abspath(fileName)
        for output in outputs:
            print ' >', output.name()
            output.store(fileName)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))


