#!/usr/bin/python
import sys
import json
import os
import argparse

import datajunction.datajunction

def main(argv):

    parser = argparse.ArgumentParser(description='Datajunction backup utility.')
    parser.add_argument('files', metavar='F', type=str, nargs='+',
                   help='files to write to output storages')

    args = parser.parse_args()
    outputs = datajunction.datajunction.loadOutputs()
    for fileName in args.files:
        print fileName
        fileName = os.path.abspath(fileName)
        for output in outputs:
            print ' >', output.name()
            output.store(fileName)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))


